version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '02:00'
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '02:30'
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci

  - package-ecosystem: gradle
    directory: /examples/standalone-consumer
    schedule:
      interval: weekly
      day: monday
      time: '02:15'
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
