org.gradle.caching=true
org.gradle.parallel=false
org.gradle.warning.mode=all

shardingSphereVersion=5.5.3
shardingSphereJacksonVersion=2.18.9
transmittableThreadLocalVersion=2.14.2
jacksonVersion=3.1.5
junitVersion=5.14.3
testcontainersVersion=1.21.4
commonsCompressVersion=1.26.0
mysqlConnectorVersion=26.7.0
hikariVersion=6.2.1
slf4jVersion=2.0.17
datasourceProxyVersion=1.11.0
