#!/usr/bin/env python3
"""Validate the twelve release SBOMs with one checksum-pinned official CLI.

This wrapper adds an independent CycloneDX schema implementation to the
project's producer-specific checks.  It deliberately validates only the six
named JSON/XML pairs generated by ``prepareVerifiedSbom``.  Passing this gate
does not establish dependency completeness, vulnerability status, or a legal
conclusion.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import platform
import re
import ssl
import stat
import subprocess
import sys
import tempfile
from typing import Any, Iterable, Mapping, Sequence
import urllib.parse
import urllib.request


EXPECTED_TOOL_NAME = "CycloneDX CLI"
EXPECTED_VERSION = "0.33.1"
EXPECTED_RELEASE_TAG = "v0.33.1"
EXPECTED_SOURCE_REPOSITORY = "https://github.com/CycloneDX/cyclonedx-cli"
EXPECTED_SOURCE_COMMIT = "b3cfa4b0edc356dad07e0b6e7ab6da0a94af0246"
EXPECTED_VERSION_OUTPUT = f"{EXPECTED_VERSION}+{EXPECTED_SOURCE_COMMIT}\n"
EXPECTED_ASSET_NAMES = {
    "darwin-arm64": "cyclonedx-osx-arm64",
    "darwin-x86_64": "cyclonedx-osx-x64",
    "linux-x86_64": "cyclonedx-linux-x64",
}
EXPECTED_PAIR_ROLES = (
    "aggregate",
    "core",
    "adapter553",
    "adapter552",
    "mysql553",
    "mysql552",
)
ALLOWED_DOWNLOAD_HOSTS = frozenset(
    {
        "github.com",
        "objects.githubusercontent.com",
        "release-assets.githubusercontent.com",
    }
)
SHA256_PATTERN = re.compile(r"[0-9a-f]{64}")
COMMIT_PATTERN = re.compile(r"[0-9a-f]{40}")
MAX_LOCK_SIZE = 64 * 1024
DOWNLOAD_CHUNK_SIZE = 1024 * 1024
DOWNLOAD_TIMEOUT_SECONDS = 120
COMMAND_TIMEOUT_SECONDS = 120

LOCK_RELATIVE_PATH = Path("security/cyclonedx-cli.lock.json")
CACHE_RELATIVE_PATH = Path("build/security-tools/cyclonedx-cli")
SBOM_PAIRS = (
    (
        "aggregate",
        Path("build/reports/verified-sbom/aggregate/bom.json"),
        Path("build/reports/verified-sbom/aggregate/bom.xml"),
    ),
    (
        "core",
        Path("build/reports/verified-sbom/routecontract-core/bom.json"),
        Path("build/reports/verified-sbom/routecontract-core/bom.xml"),
    ),
    (
        "adapter553",
        Path(
            "build/reports/verified-sbom/"
            "routecontract-shardingsphere-5.5/bom.json"
        ),
        Path(
            "build/reports/verified-sbom/"
            "routecontract-shardingsphere-5.5/bom.xml"
        ),
    ),
    (
        "adapter552",
        Path(
            "build/reports/verified-sbom/"
            "routecontract-shardingsphere-5.5.2/bom.json"
        ),
        Path(
            "build/reports/verified-sbom/"
            "routecontract-shardingsphere-5.5.2/bom.xml"
        ),
    ),
    (
        "mysql553",
        Path("build/reports/verified-sbom/mysql-example/bom.json"),
        Path("build/reports/verified-sbom/mysql-example/bom.xml"),
    ),
    (
        "mysql552",
        Path("build/reports/verified-sbom/mysql-5.5.2-example/bom.json"),
        Path("build/reports/verified-sbom/mysql-5.5.2-example/bom.xml"),
    ),
)


class CycloneDxValidationError(RuntimeError):
    """The official validator could not run under the pinned contract."""


@dataclass(frozen=True)
class Asset:
    platform: str
    name: str
    url: str
    sha256: str
    size: int


@dataclass(frozen=True)
class Lock:
    version: str
    source_commit: str
    platforms: Mapping[str, Asset]


@dataclass(frozen=True)
class FileFingerprint:
    device: int
    inode: int
    size: int
    modified_ns: int
    sha256: str


def _fail(message: str) -> CycloneDxValidationError:
    return CycloneDxValidationError(message)


def _reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise _fail(f"CycloneDX CLI lock contains duplicate key: {key}")
        result[key] = value
    return result


def _reject_non_json_number(value: str) -> None:
    raise _fail(f"CycloneDX CLI lock contains non-JSON number: {value}")


def _require_exact_keys(
    value: Any, expected: set[str], location: str
) -> dict[str, Any]:
    if type(value) is not dict:
        raise _fail(f"CycloneDX CLI lock {location} must be an object")
    actual = set(value)
    if actual != expected:
        missing = sorted(expected - actual)
        extra = sorted(actual - expected)
        raise _fail(
            f"CycloneDX CLI lock {location} has unexpected keys "
            f"(missing={missing}, extra={extra})"
        )
    return value


def _require_exact_string(value: Any, expected: str, location: str) -> str:
    if type(value) is not str or value != expected:
        raise _fail(f"CycloneDX CLI lock {location} must equal {expected!r}")
    return value


def _canonical_regular_directory(directory: Path, label: str) -> Path:
    raw = Path(directory)
    if not raw.is_absolute():
        raw = Path.cwd() / raw
    try:
        raw_status = os.lstat(raw)
    except OSError as error:
        raise _fail(f"cannot inspect {label}: {error}") from None
    if stat.S_ISLNK(raw_status.st_mode) or not stat.S_ISDIR(raw_status.st_mode):
        raise _fail(f"{label} must be a regular non-symlink directory")
    try:
        resolved = raw.resolve(strict=True)
    except OSError as error:
        raise _fail(f"cannot resolve {label}: {error}") from None
    if resolved != raw:
        raise _fail(f"{label} must be supplied as its canonical absolute path")
    return resolved


def _canonical_repository_root(repository_root: Path) -> Path:
    return _canonical_regular_directory(repository_root, "repository root")


def _path_under_root(root: Path, supplied_path: Path) -> Path:
    if not supplied_path.parts:
        raise _fail(f"unsafe rooted path: {supplied_path}")
    if supplied_path.is_absolute():
        raise _fail(f"rooted input path must be relative: {supplied_path}")
    if any(part in ("", ".", "..") for part in supplied_path.parts):
        raise _fail(f"unsafe rooted path: {supplied_path}")
    candidate = root.joinpath(*supplied_path.parts)
    try:
        candidate.relative_to(root)
    except ValueError:
        raise _fail(f"path escapes supplied root: {supplied_path}") from None
    return candidate


def _assert_no_symlink_components(
    repository_root: Path, path: Path, *, allow_missing: bool
) -> None:
    try:
        relative = path.relative_to(repository_root)
    except ValueError:
        raise _fail(f"path escapes repository root: {path}") from None
    current = repository_root
    for part in relative.parts:
        current /= part
        try:
            current_status = os.lstat(current)
        except FileNotFoundError:
            if allow_missing:
                return
            raise _fail(f"required path does not exist: {path}") from None
        except OSError as error:
            raise _fail(f"cannot inspect required path {path}: {error}") from None
        if stat.S_ISLNK(current_status.st_mode):
            raise _fail(f"symbolic links are not allowed: {current}")


def _regular_file_status(repository_root: Path, path: Path) -> os.stat_result:
    _assert_no_symlink_components(repository_root, path, allow_missing=False)
    try:
        result = os.lstat(path)
    except OSError as error:
        raise _fail(f"cannot inspect required file {path}: {error}") from None
    if not stat.S_ISREG(result.st_mode):
        raise _fail(f"required path is not a regular file: {path}")
    return result


def _open_regular_file(repository_root: Path, path: Path) -> tuple[int, os.stat_result]:
    before = _regular_file_status(repository_root, path)
    flags = os.O_RDONLY
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    try:
        descriptor = os.open(path, flags)
    except OSError as error:
        raise _fail(f"cannot open required file {path}: {error}") from None
    try:
        opened = os.fstat(descriptor)
        if not stat.S_ISREG(opened.st_mode):
            raise _fail(f"opened path is not a regular file: {path}")
        if (before.st_dev, before.st_ino) != (opened.st_dev, opened.st_ino):
            raise _fail(f"required file changed while opening: {path}")
    except Exception:
        os.close(descriptor)
        raise
    return descriptor, opened


def _fingerprint_regular_file(
    repository_root: Path, path: Path
) -> FileFingerprint:
    descriptor, before = _open_regular_file(repository_root, path)
    digest = hashlib.sha256()
    total = 0
    try:
        while True:
            block = os.read(descriptor, DOWNLOAD_CHUNK_SIZE)
            if not block:
                break
            total += len(block)
            digest.update(block)
        after = os.fstat(descriptor)
    except OSError as error:
        raise _fail(f"cannot fingerprint required file {path}: {error}") from None
    finally:
        os.close(descriptor)
    final = _regular_file_status(repository_root, path)
    identity_before = (
        before.st_dev,
        before.st_ino,
        before.st_size,
        before.st_mtime_ns,
    )
    identity_after = (
        after.st_dev,
        after.st_ino,
        after.st_size,
        after.st_mtime_ns,
    )
    identity_final = (
        final.st_dev,
        final.st_ino,
        final.st_size,
        final.st_mtime_ns,
    )
    if identity_before != identity_after or identity_after != identity_final:
        raise _fail(f"required file changed while fingerprinting: {path}")
    if total != final.st_size:
        raise _fail(f"required file size changed while fingerprinting: {path}")
    return FileFingerprint(
        device=final.st_dev,
        inode=final.st_ino,
        size=total,
        modified_ns=final.st_mtime_ns,
        sha256=digest.hexdigest(),
    )


def _read_small_regular_file(
    repository_root: Path, path: Path, maximum_size: int
) -> tuple[bytes, FileFingerprint]:
    descriptor, before = _open_regular_file(repository_root, path)
    data = bytearray()
    digest = hashlib.sha256()
    try:
        while True:
            block = os.read(descriptor, min(DOWNLOAD_CHUNK_SIZE, maximum_size + 1))
            if not block:
                break
            data.extend(block)
            digest.update(block)
            if len(data) > maximum_size:
                raise _fail(f"required file is unexpectedly large: {path}")
        after = os.fstat(descriptor)
    except OSError as error:
        raise _fail(f"cannot read required file {path}: {error}") from None
    finally:
        os.close(descriptor)
    final = _regular_file_status(repository_root, path)
    identities = {
        (before.st_dev, before.st_ino, before.st_size, before.st_mtime_ns),
        (after.st_dev, after.st_ino, after.st_size, after.st_mtime_ns),
        (final.st_dev, final.st_ino, final.st_size, final.st_mtime_ns),
    }
    if len(identities) != 1 or len(data) != final.st_size:
        raise _fail(f"required file changed while reading: {path}")
    fingerprint = FileFingerprint(
        device=final.st_dev,
        inode=final.st_ino,
        size=final.st_size,
        modified_ns=final.st_mtime_ns,
        sha256=digest.hexdigest(),
    )
    return bytes(data), fingerprint


def load_lock(
    repository_root: Path, lock_path: Path
) -> tuple[Lock, FileFingerprint]:
    raw, fingerprint = _read_small_regular_file(
        repository_root, lock_path, MAX_LOCK_SIZE
    )
    try:
        text = raw.decode("utf-8", errors="strict")
        document = json.loads(
            text,
            object_pairs_hook=_reject_duplicate_keys,
            parse_constant=_reject_non_json_number,
        )
    except CycloneDxValidationError:
        raise
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise _fail(f"CycloneDX CLI lock is not strict UTF-8 JSON: {error}") from None

    root = _require_exact_keys(document, {"schemaVersion", "tool"}, "root")
    if type(root["schemaVersion"]) is not int or root["schemaVersion"] != 1:
        raise _fail("CycloneDX CLI lock schemaVersion must equal integer 1")
    tool = _require_exact_keys(
        root["tool"],
        {
            "name",
            "version",
            "releaseTag",
            "sourceRepository",
            "sourceCommit",
            "platforms",
        },
        "tool",
    )
    _require_exact_string(tool["name"], EXPECTED_TOOL_NAME, "tool.name")
    version = _require_exact_string(
        tool["version"], EXPECTED_VERSION, "tool.version"
    )
    _require_exact_string(
        tool["releaseTag"], EXPECTED_RELEASE_TAG, "tool.releaseTag"
    )
    _require_exact_string(
        tool["sourceRepository"],
        EXPECTED_SOURCE_REPOSITORY,
        "tool.sourceRepository",
    )
    source_commit = _require_exact_string(
        tool["sourceCommit"], EXPECTED_SOURCE_COMMIT, "tool.sourceCommit"
    )
    if COMMIT_PATTERN.fullmatch(source_commit) is None:  # defensive exact shape
        raise _fail("CycloneDX CLI source commit is not lowercase 40-hex")

    platforms = _require_exact_keys(
        tool["platforms"], set(EXPECTED_ASSET_NAMES), "tool.platforms"
    )
    parsed_assets: dict[str, Asset] = {}
    for platform_name in sorted(EXPECTED_ASSET_NAMES):
        entry = _require_exact_keys(
            platforms[platform_name],
            {"asset", "url", "sha256", "size"},
            f"tool.platforms.{platform_name}",
        )
        asset_name = _require_exact_string(
            entry["asset"],
            EXPECTED_ASSET_NAMES[platform_name],
            f"tool.platforms.{platform_name}.asset",
        )
        expected_url = (
            f"{EXPECTED_SOURCE_REPOSITORY}/releases/download/"
            f"{EXPECTED_RELEASE_TAG}/{asset_name}"
        )
        url = _require_exact_string(
            entry["url"], expected_url, f"tool.platforms.{platform_name}.url"
        )
        sha256 = entry["sha256"]
        if type(sha256) is not str or SHA256_PATTERN.fullmatch(sha256) is None:
            raise _fail(
                f"CycloneDX CLI lock tool.platforms.{platform_name}.sha256 "
                "must be lowercase 64-hex"
            )
        size = entry["size"]
        if type(size) is not int or size <= 0:
            raise _fail(
                f"CycloneDX CLI lock tool.platforms.{platform_name}.size "
                "must be a positive integer"
            )
        parsed_assets[platform_name] = Asset(
            platform=platform_name,
            name=asset_name,
            url=url,
            sha256=sha256,
            size=size,
        )
    if len({asset.sha256 for asset in parsed_assets.values()}) != len(parsed_assets):
        raise _fail("CycloneDX CLI platform assets must have distinct SHA-256 values")
    return (
        Lock(
            version=version,
            source_commit=source_commit,
            platforms=parsed_assets,
        ),
        fingerprint,
    )


def detect_platform() -> str:
    identity = (platform.system(), platform.machine())
    supported = {
        ("Darwin", "arm64"): "darwin-arm64",
        ("Darwin", "x86_64"): "darwin-x86_64",
        ("Linux", "x86_64"): "linux-x86_64",
    }
    try:
        return supported[identity]
    except KeyError:
        raise _fail(
            "unsupported CycloneDX CLI platform: " + ":".join(identity)
        ) from None


def _ensure_directory_chain(repository_root: Path, relative_path: Path) -> Path:
    directory = repository_root
    for part in relative_path.parts:
        directory /= part
        try:
            current = os.lstat(directory)
        except FileNotFoundError:
            try:
                os.mkdir(directory, 0o700)
            except FileExistsError:
                pass
            except OSError as error:
                raise _fail(
                    f"cannot create cache directory {directory}: {error}"
                ) from None
            try:
                current = os.lstat(directory)
            except OSError as error:
                raise _fail(
                    f"cannot inspect cache directory {directory}: {error}"
                ) from None
        except OSError as error:
            raise _fail(
                f"cannot inspect cache directory {directory}: {error}"
            ) from None
        if stat.S_ISLNK(current.st_mode) or not stat.S_ISDIR(current.st_mode):
            raise _fail(
                f"cache path component is not a regular directory: {directory}"
            )
    return directory


def _validate_download_url(url: str) -> None:
    parsed = urllib.parse.urlsplit(url)
    if (
        parsed.scheme != "https"
        or parsed.hostname not in ALLOWED_DOWNLOAD_HOSTS
        or parsed.username is not None
        or parsed.password is not None
    ):
        raise _fail("CycloneDX CLI download did not remain on an allowed HTTPS host")


def _response_header(response: Any, name: str) -> str | None:
    headers = getattr(response, "headers", None)
    if headers is None:
        return None
    value = headers.get(name)
    return None if value is None else str(value)


def _verified_tls_context() -> ssl.SSLContext:
    """Build a verified context, including common OS bundles for python.org Python."""
    context = ssl.create_default_context()
    default_paths = ssl.get_default_verify_paths()
    if default_paths.cafile is None:
        for candidate in (
            Path("/etc/ssl/cert.pem"),
            Path("/etc/ssl/certs/ca-certificates.crt"),
            Path("/etc/pki/tls/certs/ca-bundle.crt"),
        ):
            try:
                candidate_status = os.stat(candidate)
            except OSError:
                continue
            if not stat.S_ISREG(candidate_status.st_mode):
                continue
            try:
                context.load_verify_locations(cafile=str(candidate))
            except (OSError, ssl.SSLError):
                continue
            break
    context.check_hostname = True
    context.verify_mode = ssl.CERT_REQUIRED
    context.minimum_version = ssl.TLSVersion.TLSv1_2
    return context


def _download_verified(asset: Asset, repository_root: Path, destination: Path) -> None:
    _validate_download_url(asset.url)
    _assert_no_symlink_components(repository_root, destination, allow_missing=True)
    if os.path.lexists(destination):
        raise _fail("refusing to replace an existing CycloneDX CLI cache entry")

    temporary_descriptor = -1
    temporary_path: Path | None = None
    try:
        temporary_descriptor, temporary_name = tempfile.mkstemp(
            prefix=".cyclonedx-download-", dir=destination.parent
        )
        temporary_path = Path(temporary_name)
        os.fchmod(temporary_descriptor, 0o600)
        request = urllib.request.Request(
            asset.url,
            headers={"User-Agent": "RouteContract-CycloneDX-validator/1"},
            method="GET",
        )
        digest = hashlib.sha256()
        total = 0
        with os.fdopen(temporary_descriptor, "wb", closefd=True) as output:
            temporary_descriptor = -1
            with urllib.request.urlopen(
                request,
                timeout=DOWNLOAD_TIMEOUT_SECONDS,
                context=_verified_tls_context(),
            ) as response:
                status_code = getattr(response, "status", None)
                if type(status_code) is not int or status_code != 200:
                    raise _fail("CycloneDX CLI download did not return HTTP 200")
                final_url = (
                    response.geturl() if hasattr(response, "geturl") else asset.url
                )
                _validate_download_url(str(final_url))
                content_encoding = _response_header(response, "Content-Encoding")
                if content_encoding not in (None, "", "identity"):
                    raise _fail("CycloneDX CLI download used unexpected content encoding")
                content_length = _response_header(response, "Content-Length")
                if content_length is not None:
                    try:
                        declared_size = int(content_length, 10)
                    except ValueError:
                        raise _fail(
                            "CycloneDX CLI download Content-Length is invalid"
                        ) from None
                    if declared_size != asset.size:
                        raise _fail(
                            "CycloneDX CLI download Content-Length does not match lock"
                        )
                while True:
                    block = response.read(DOWNLOAD_CHUNK_SIZE)
                    if not isinstance(block, bytes):
                        raise _fail("CycloneDX CLI download returned non-byte content")
                    if not block:
                        break
                    total += len(block)
                    if total > asset.size:
                        raise _fail("CycloneDX CLI download exceeds locked size")
                    digest.update(block)
                    output.write(block)
            output.flush()
            os.fsync(output.fileno())
        if total != asset.size:
            raise _fail("CycloneDX CLI download size does not match lock")
        if digest.hexdigest() != asset.sha256:
            raise _fail("CycloneDX CLI download SHA-256 does not match lock")

        temporary_status = os.lstat(temporary_path)
        if not stat.S_ISREG(temporary_status.st_mode):
            raise _fail("CycloneDX CLI temporary download is not a regular file")
        os.chmod(temporary_path, 0o500)
        # Publish without replacement.  Because the temporary file is in the
        # same directory, hard-link creation is atomic and fails if another
        # process creates any destination entry after the earlier inspection.
        try:
            os.link(temporary_path, destination, follow_symlinks=False)
        except FileExistsError:
            raise _fail("CycloneDX CLI cache entry appeared during download") from None
        except OSError as error:
            raise _fail(
                "could not atomically publish the verified CycloneDX CLI: "
                f"{type(error).__name__}"
            ) from None
        temporary_path.unlink()
        temporary_path = None
        try:
            directory_descriptor = os.open(destination.parent, os.O_RDONLY)
        except OSError:
            directory_descriptor = -1
        if directory_descriptor >= 0:
            try:
                os.fsync(directory_descriptor)
            except OSError:
                pass
            finally:
                os.close(directory_descriptor)
    except CycloneDxValidationError:
        raise
    except Exception as error:
        raise _fail(f"could not download pinned CycloneDX CLI: {type(error).__name__}") from None
    finally:
        if temporary_descriptor >= 0:
            os.close(temporary_descriptor)
        if temporary_path is not None:
            try:
                temporary_path.unlink(missing_ok=True)
            except OSError:
                pass


def _require_expected_asset(
    repository_root: Path, path: Path, asset: Asset
) -> FileFingerprint:
    fingerprint = _fingerprint_regular_file(repository_root, path)
    if fingerprint.size != asset.size or fingerprint.sha256 != asset.sha256:
        raise _fail(
            "existing CycloneDX CLI cache entry does not match its locked content"
        )
    try:
        mode = os.lstat(path).st_mode
    except OSError as error:
        raise _fail(f"cannot inspect CycloneDX CLI executable mode: {error}") from None
    if mode & (stat.S_IWGRP | stat.S_IWOTH):
        raise _fail("CycloneDX CLI cache entry must not be group/world writable")
    if not mode & stat.S_IXUSR:
        try:
            os.chmod(path, stat.S_IMODE(mode) | stat.S_IXUSR)
        except OSError as error:
            raise _fail(f"cannot make CycloneDX CLI cache entry executable: {error}") from None
        fingerprint = _fingerprint_regular_file(repository_root, path)
    return fingerprint


def prepare_binary(
    repository_root: Path, asset: Asset, *, offline: bool
) -> tuple[Path, FileFingerprint]:
    checksum_directory = _ensure_directory_chain(
        repository_root, CACHE_RELATIVE_PATH / asset.sha256
    )
    binary = checksum_directory / "cyclonedx"
    _assert_no_symlink_components(repository_root, binary, allow_missing=True)
    if os.path.lexists(binary):
        return binary, _require_expected_asset(repository_root, binary, asset)
    if offline:
        raise _fail(
            "offline mode requires the checksum-addressed CycloneDX CLI cache entry"
        )
    _download_verified(asset, repository_root, binary)
    return binary, _require_expected_asset(repository_root, binary, asset)


def _snapshot_files(
    repository_root: Path, paths: Iterable[Path]
) -> dict[Path, FileFingerprint]:
    return {
        path: _fingerprint_regular_file(repository_root, path)
        for path in paths
    }


def _require_unchanged(
    repository_root: Path, expected: Mapping[Path, FileFingerprint]
) -> None:
    for path, fingerprint in expected.items():
        if _fingerprint_regular_file(repository_root, path) != fingerprint:
            raise _fail(f"validated input changed while the official CLI ran: {path}")


def _normalize_sbom_pairs(
    input_root: Path,
    sbom_pairs: Sequence[tuple[str, Path, Path]] | None,
) -> tuple[tuple[str, Path, Path], ...]:
    supplied = SBOM_PAIRS if sbom_pairs is None else tuple(sbom_pairs)
    if len(supplied) != 6:
        raise _fail("official CycloneDX validation requires exactly six SBOM pairs")
    by_role: dict[str, tuple[Path, Path]] = {}
    for item in supplied:
        if type(item) is not tuple or len(item) != 3:
            raise _fail("each CycloneDX SBOM pair must be a role, JSON path, XML path")
        role, raw_json, raw_xml = item
        if type(role) is not str or role not in EXPECTED_PAIR_ROLES:
            raise _fail(f"unexpected CycloneDX SBOM pair role: {role!r}")
        if role in by_role:
            raise _fail(f"duplicate CycloneDX SBOM pair role: {role}")
        if not isinstance(raw_json, Path) or not isinstance(raw_xml, Path):
            raise _fail("CycloneDX SBOM pair paths must be pathlib.Path values")
        json_path = _path_under_root(input_root, raw_json)
        xml_path = _path_under_root(input_root, raw_xml)
        if json_path.suffix != ".json" or xml_path.suffix != ".xml":
            raise _fail(
                f"CycloneDX SBOM pair {role} must name one .json and one .xml file"
            )
        by_role[role] = (json_path, xml_path)
    if set(by_role) != set(EXPECTED_PAIR_ROLES):
        raise _fail(
            "CycloneDX SBOM pair roles must be aggregate, core, adapter553, "
            "adapter552, mysql553 and mysql552"
        )
    normalized = tuple(
        (role, by_role[role][0], by_role[role][1])
        for role in EXPECTED_PAIR_ROLES
    )
    paths = [path for _, json_path, xml_path in normalized for path in (json_path, xml_path)]
    if len(set(paths)) != 12:
        raise _fail("CycloneDX validation requires twelve distinct SBOM files")
    return normalized


def _run_command(
    arguments: list[str], repository_root: Path
) -> subprocess.CompletedProcess[str]:
    if not arguments or not Path(arguments[0]).is_absolute():
        raise _fail("CycloneDX CLI must be invoked by an absolute executable path")
    try:
        return subprocess.run(
            arguments,
            cwd=repository_root,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            errors="strict",
            check=False,
            timeout=COMMAND_TIMEOUT_SECONDS,
            close_fds=True,
        )
    except (OSError, UnicodeError, subprocess.TimeoutExpired) as error:
        raise _fail(
            "could not execute pinned CycloneDX CLI: " + type(error).__name__
        ) from None


def _run_protected_command(
    arguments: list[str],
    repository_root: Path,
    fingerprints_by_root: Sequence[
        tuple[Path, Mapping[Path, FileFingerprint]]
    ],
) -> subprocess.CompletedProcess[str]:
    try:
        return _run_command(arguments, repository_root)
    finally:
        for fingerprint_root, fingerprints in fingerprints_by_root:
            _require_unchanged(fingerprint_root, fingerprints)


def validate_repository(
    repository_root: Path,
    *,
    offline: bool,
    sbom_pairs: Sequence[tuple[str, Path, Path]] | None = None,
    input_root: Path | None = None,
) -> int:
    root = _canonical_repository_root(repository_root)
    if input_root is None:
        document_root = root
    else:
        document_root = _canonical_regular_directory(input_root, "SBOM input root")
    if (sbom_pairs is None) != (input_root is None):
        raise _fail(
            "an explicit SBOM input root and exactly six pairs must be supplied together"
        )
    normalized_pairs = _normalize_sbom_pairs(document_root, sbom_pairs)
    lock_path = _path_under_root(root, LOCK_RELATIVE_PATH)
    lock, lock_fingerprint = load_lock(root, lock_path)
    platform_name = detect_platform()
    try:
        asset = lock.platforms[platform_name]
    except KeyError:
        raise _fail(f"CycloneDX CLI lock has no asset for {platform_name}") from None
    binary, binary_fingerprint = prepare_binary(root, asset, offline=offline)

    documents: list[tuple[str, str, Path]] = []
    for pair_name, json_path, xml_path in normalized_pairs:
        documents.append((pair_name, "json", json_path))
        documents.append((pair_name, "xml", xml_path))
    if len(documents) != 12 or len({name for name, _, _ in documents}) != 6:
        raise _fail("internal CycloneDX validation set must be exactly six named pairs")
    if {format_name for _, format_name, _ in documents} != {"json", "xml"}:
        raise _fail("internal CycloneDX validation set must contain JSON and XML")

    repository_protected_paths = [lock_path, binary]
    repository_fingerprints = _snapshot_files(root, repository_protected_paths)
    document_paths = [path for _, _, path in documents]
    document_fingerprints = _snapshot_files(document_root, document_paths)
    fingerprints_by_root = (
        (root, repository_fingerprints),
        (document_root, document_fingerprints),
    )
    if repository_fingerprints[lock_path] != lock_fingerprint:
        raise _fail("CycloneDX CLI lock changed after parsing")
    if repository_fingerprints[binary] != binary_fingerprint:
        raise _fail("CycloneDX CLI cache entry changed after verification")

    version_result = _run_protected_command(
        [str(binary), "--version"], root, fingerprints_by_root
    )
    if (
        version_result.returncode != 0
        or version_result.stdout != EXPECTED_VERSION_OUTPUT
        or version_result.stderr != ""
    ):
        raise _fail(
            "CycloneDX CLI --version output does not match the locked version and commit"
        )

    for pair_name, format_name, input_path in documents:
        if not input_path.is_absolute():  # defensive; all paths above are rooted
            raise _fail("CycloneDX input path must be absolute")
        result = _run_protected_command(
            [
                str(binary),
                "validate",
                "--input-file",
                str(input_path),
                "--input-format",
                format_name,
                "--input-version",
                "v1_6",
                "--fail-on-errors",
            ],
            root,
            fingerprints_by_root,
        )
        if result.returncode != 0:
            raise _fail(
                f"official CycloneDX validation failed for {pair_name}/{format_name}"
            )
    return len(documents)


def _repository_root_from_script() -> Path:
    raw_script = Path(__file__)
    if not raw_script.is_absolute():
        raw_script = Path.cwd() / raw_script
    try:
        raw_status = os.lstat(raw_script)
    except OSError as error:
        raise _fail(f"cannot inspect validator script: {error}") from None
    if stat.S_ISLNK(raw_status.st_mode) or not stat.S_ISREG(raw_status.st_mode):
        raise _fail("validator script must be a regular non-symlink file")
    try:
        script = raw_script.resolve(strict=True)
    except OSError as error:
        raise _fail(f"cannot resolve validator script: {error}") from None
    root = script.parents[1]
    _assert_no_symlink_components(root, script, allow_missing=False)
    return _canonical_repository_root(root)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate all six RouteContract SBOM pairs with CycloneDX CLI 0.33.1",
        allow_abbrev=False,
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help="reject a missing cache entry instead of downloading the pinned binary",
    )
    parser.add_argument(
        "--pair",
        action="append",
        nargs=3,
        metavar=("ROLE", "JSON", "XML"),
        help=(
            "validate an explicit role/path tuple; repeat exactly for aggregate, "
            "core, adapter553, adapter552, mysql553 and mysql552, or omit all six "
            "for generated build paths"
        ),
    )
    parser.add_argument(
        "--input-root",
        type=Path,
        help=(
            "canonical directory anchoring all explicit --pair paths; required "
            "when --pair is used and may be outside the repository"
        ),
    )
    arguments = parser.parse_args(argv)
    try:
        root = _repository_root_from_script()
        explicit_pairs = None
        if arguments.pair is not None:
            if arguments.input_root is None:
                raise _fail("explicit --pair values require --input-root")
            explicit_pairs = tuple(
                (role, Path(json_path), Path(xml_path))
                for role, json_path, xml_path in arguments.pair
            )
        elif arguments.input_root is not None:
            raise _fail("--input-root requires exactly six --pair values")
        document_count = validate_repository(
            root,
            offline=arguments.offline,
            sbom_pairs=explicit_pairs,
            input_root=arguments.input_root,
        )
    except CycloneDxValidationError as error:
        print(f"OFFICIAL_CYCLONEDX_VALIDATION_FAILED: {error}", file=sys.stderr)
        return 2
    print(
        "OFFICIAL_CYCLONEDX_VALIDATION_OK "
        f"version={EXPECTED_VERSION} source_commit={EXPECTED_SOURCE_COMMIT} "
        f"pairs=6 documents={document_count}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
